### PR TITLE
migrate to python3 and clean some things

### PR DESCRIPTION
**Pull request by Jibec**
Hi there, I started to rewrite this good script.

I wanted to make more with this script, and rewriting everything helps me to understand the code.
A check file is here to make sure I don't destroy what I don't understand while working...

I think I'll use numpy to compute centroid and area.

I can't understand why we are doing some things, like "density" computation.

### CODE REVIEW

**Comment by sebastien-bugzilla** [comment]
Hello Jean-Baptiste and many thanks for your contributions and improvements. I will merge your propositions. 
To be honest I don't use it anymore but I'm happy that it is still used by someone.
It's not very clear why I choose to log the building density. I agree it's not useful. I use the building zone to avoid to compare each building of old version to all building of new version and be faster. At first, I didn't know which value I should put for NB_ZONE_USER. I remember I took low values like 5 or 10. It was improving the comparison but I tried to increase the number and noticed it was faster. I end up with the value of 500.

Have a nice day.

Sébastien

**Comment by Jibec** [comment]
hi Sebastien, thanks for your feedback. Did you had time to test this PR works for you?

It runs, but I have doubts, I've tried with city of Rothau, but josm tells me the osm files are not valid for the deleted buildings.

How do you feel about BatiOsm project, would you like to help me? Reviews and question/answer would be fine, if testing or even coding is too time consuming.

I'd like to improve test coverage as a first step. Through existing known working files and the basic test script I have done.

**Comment by sebastien-bugzilla** [comment]
Hi. 
To be honest I hadn't checked your modifications. Today, I took some time to do it now. Everything seems to be OK. I used the data for the city of Buzy you have in your fork.
If you can provide me the file for Rothau I could test them and see if I see something strange.
For the project BatiOsm sure I can help you. I'm not a professional programmer (as you might have noticed) but I can explain the choice I've made.

**Comment by Jibec** [comment]
Happy to read this! Thanks for being available to do this together.
I'm in the software development business, but not a dev either. Simply trying to understand how it works and how to improve it so that it gets included in cadastre.openstreetmap.fr and damsy someday.
Neither osmfr tool or damsy suis me, it consumes way too much time.
Damsy uses qgis and complex stuff I don't want to learn. Same for osmfr stuff. I need something I can try multiple times before submitting it.
Is there a place where we can discuss between french talking osm devs? IRC or equivalent? Or if you prefer, email works for me: Jean-Baptiste arobase Holcroft point fr

**Pull request merged**
